### ISSUE TITLE
negative infinity

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/purescript-numbers#20]
Do we need negative infinity too? I think so?

https://github.com/purescript/purescript-numbers/blob/f5bbd96cbed58403c4445bd4c73df50fc8d86f46/src/Data/Number.js#L8

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity

**Comment by JamieBallingall** [comment]
I don't think that there is any occasion where negative infinity is actually necessary because you can always use `(-infinity)` which, I'm pretty sure, is guaranteed to be the same.

I think it is a fairly easy and safe addition, provided we are ok with the slightly odd naming of `infinity` and `negative_infinity` rather than `positive_infinity` and `negative_infinity`. The later is more consistent with Javascript but is a breaking change.

**Comment by jamesdbrock** [comment]
That makes sense.
